DROP TABLE IF EXISTS ADJD_CLMHST_CLM;

CREATE TABLE ADJD_CLMHST_CLM (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  partnId VARCHAR(250) NOT NULL,
  partVal VARCHAR(250) NOT NULL,
  invnCtlNbr VARCHAR(250) DEFAULT NULL
);